# Generated by Django 5.0.7 on 2025-07-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyTrail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_code',
            new_name='api_external_id',
        ),
    ]
